### PR TITLE
Add Seasonal Forecasting Tutorial Notebooks

### PR DESCRIPTION
**Pull request by ankurmahesh**
Adds the seasonal forecasting notebooks for the hackathon

### CODE REVIEW

**Comment by djgagne** [comment]
The material in the notebooks generally looks good to me, but I would like you to make some edits so that this notebook is more consistent with the other challenge problems. 
* Can you merge the 2 notebooks into 1 larger notebook?
* Can you edit the notebooks to make them more consistent with the other hackathon challenge problems?
  * In particular, remove the Essential Reading, 2 Hackathon Problems, and 2 Takehome Problems at the end of part 1.
  * Remove the links to the Kaggle page and change the name of the section to Baseline ML. 
  * Remove the Challenge exercises and BONUS fun exercises.
  * Add the cells from the end of the [template notebook](https://github.com/NCAR/ai4ess-hackathon-2020/blob/master/notebooks/template.ipynb).

**Comment by ankurmahesh** [comment]
Thanks for the feedback.  I'll make those edits and also remove some more informal portions of the notebook: i.e. writing out "WOOHOO".

I will remove the sections that you indicated.  I have two questions:

1. Would it be possible to keep the "challenge" exercises? As I designed the hackathon, I intended for the challenge problems to be a vital part of it. Even though there are only 2, these 2 problems should take a third of the hackathon time.  Without these two problems, there may not be enough material to fill the entire hackathon *for some teams*.  These challenge exercises are really the goal of the hackathon: being able to train a model to forecast seasonal temperature at any location, and being able to train a reasonably complicated architecture (CNN+LSTM).  The "challenge" exercises aren't really any different from the other ones in terms of their content/ material/ relevance to the hackathon.  I just marked them as "challenge" so that attendees are aware that they likely will take longer.  Perhaps calling them "challenge exercises" wasn't appropriate?  

2. Would it be possible to keep the Kaggle page? At Karthik's recommendation, I made this kaggle page specifically for the hackathon to allow folks to benchmark different algorithms and algorithms with each other.   This would be part of (but not all) the criteria that we use to select a team to present on Friday.

**Comment by djgagne** [comment]
1. Can you call them practice exercises instead? I am using the term challenge to describe each notebook, so I don't want to cause confusion there.

2. How hard is it to setup a Kaggle page for each contest? If it is free and easy, I can set up ones for the other problems too. The plan for the presentations is to have each team submit 2 slides on their approach and have one of us go through the merged set of presentations. The kaggle rankings would be a way to order them consistently.

**Comment by ankurmahesh** [comment]
1. Absolutely.  I'll make the change. Thank you.  Sorry for causing the confusion with the duplicate use of the word "challenge".

2. I found Kaggle to be extremely seamless, simple, and free.  It was straightforward to upload ground truth data in CSV format and select the benchmarking algorithm (i.e. RMSE, anomaly correlation, etc.) from a drag and drop menu.

**Comment by djgagne** [comment]
@ankurmahesh any updates to the notebooks. I would like to have them built by this afternoon so I can test scaling up of the system.

**Comment by ankurmahesh** [comment]
@djgagne: I made the changes, and I submitted them in a different pull requests.

**Pull request closed without merging**
